# Generated by Django 5.1.1 on 2025-02-17 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0002_uploadedimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Plot',
        ),
    ]
