# Generated by Django 5.1.1 on 2025-03-03 06:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0005_advertisement_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrivingTrainingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='driving_training/images/', verbose_name='Image')),
            ],
        ),
        migrations.CreateModel(
            name='DrivingTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainer_name', models.CharField(max_length=255)),
                ('trainer_gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('transmission', models.CharField(choices=[('Automatic', 'Automatic'), ('Manual', 'Manual')], max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price (OMR)')),
                ('body_type', models.CharField(choices=[('Sedan', 'Sedan'), ('Hatchback', 'Hatchback'), ('Small Truck', 'Small Truck'), ('Large Truck', 'Large Truck'), ('Motorcycle', 'Motorcycle')], max_length=20)),
                ('model_year', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField(verbose_name='Description')),
                ('regions', models.CharField(choices=[('MS', 'Muscat'), ('DH', 'Dhofar'), ('BT', 'Batinah'), ('DA', 'Dakhiliyah'), ('SH', 'Sharqiyah'), ('BR', 'Buraimi'), ('ZU', 'Zufar'), ('MW', 'Musandam'), ('WR', 'Wusta')], default='MS', max_length=250)),
                ('cities', models.TextField(max_length=250)),
                ('location', models.TextField(max_length=250)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='Approval Status')),
                ('language', models.CharField(max_length=100)),
                ('about_instructor', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driving_trainings', to=settings.AUTH_USER_MODEL)),
                ('images', models.ManyToManyField(blank=True, related_name='driving_training', to='oman_app.drivingtrainingimage', verbose_name='Images')),
            ],
        ),
    ]
