# Generated by Django 5.1.1 on 2025-03-04 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0006_drivingtrainingimage_drivingtraining'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='numberplate',
            name='images',
        ),
        migrations.RemoveField(
            model_name='numberplate',
            name='videos',
        ),
        migrations.AddField(
            model_name='numberplate',
            name='letter_arabic',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='numberplate',
            name='letter_english',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='numberplate',
            name='plate_type',
            field=models.CharField(choices=[('commercial', 'Commercial'), ('driving_training', 'Driving Training'), ('motorcycle', 'Motorcycle'), ('personal', 'Personal'), ('rental', 'Rental'), ('taxi_buses', 'Taxi Buses'), ('taxi_sedan', 'Taxi Sedan')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='numberplate',
            name='seller_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='numberplate',
            name='listing_type',
            field=models.CharField(choices=[('sell', 'Sell'), ('rent', 'Rent'), ('wanted', 'Wanted')], default='sell', max_length=10, verbose_name='Listing Type'),
        ),
        migrations.AlterField(
            model_name='numberplate',
            name='number',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.DeleteModel(
            name='NumberPlateImage',
        ),
        migrations.DeleteModel(
            name='NumberPlateVideo',
        ),
    ]
