# Generated by Django 5.1.1 on 2025-03-04 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0007_remove_numberplate_images_remove_numberplate_videos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivingtraining',
            name='latitude',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drivingtraining',
            name='longitude',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
