# Generated by Django 5.1.1 on 2025-03-04 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0008_drivingtraining_latitude_drivingtraining_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drivingtraining',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='drivingtraining',
            name='longitude',
        ),
    ]
