# Generated by Django 5.1.1 on 2025-03-04 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0009_remove_drivingtraining_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivingtraining',
            name='latitude',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drivingtraining',
            name='longitude',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='autoaccessorypart',
            name='regions',
            field=models.CharField(choices=[('MS', 'Muscat'), ('DH', 'Dhofar'), ('BT', 'Al Batinah'), ('DA', 'Al Dakhiliya'), ('SH', 'Al Sharqiya'), ('BR', 'Al Buraimi'), ('ZU', 'Al Dhahirah'), ('MW', 'Musandam'), ('WR', 'Al Wusta')], default='MS', max_length=250),
        ),
        migrations.AlterField(
            model_name='automobile',
            name='regions',
            field=models.CharField(choices=[('MS', 'Muscat'), ('DH', 'Dhofar'), ('BT', 'Al Batinah'), ('DA', 'Al Dakhiliya'), ('SH', 'Al Sharqiya'), ('BR', 'Al Buraimi'), ('ZU', 'Al Dhahirah'), ('MW', 'Musandam'), ('WR', 'Al Wusta')], default='MS', max_length=250),
        ),
        migrations.AlterField(
            model_name='boat',
            name='regions',
            field=models.CharField(choices=[('MS', 'Muscat'), ('DH', 'Dhofar'), ('BT', 'Al Batinah'), ('DA', 'Al Dakhiliya'), ('SH', 'Al Sharqiya'), ('BR', 'Al Buraimi'), ('ZU', 'Al Dhahirah'), ('MW', 'Musandam'), ('WR', 'Al Wusta')], default='MS', max_length=250),
        ),
        migrations.AlterField(
            model_name='drivingtraining',
            name='regions',
            field=models.CharField(choices=[('MS', 'Muscat'), ('DH', 'Dhofar'), ('BT', 'Al Batinah'), ('DA', 'Al Dakhiliya'), ('SH', 'Al Sharqiya'), ('BR', 'Al Buraimi'), ('ZU', 'Al Dhahirah'), ('MW', 'Musandam'), ('WR', 'Al Wusta')], default='MS', max_length=250),
        ),
        migrations.AlterField(
            model_name='heavyvehicle',
            name='regions',
            field=models.CharField(choices=[('MS', 'Muscat'), ('DH', 'Dhofar'), ('BT', 'Al Batinah'), ('DA', 'Al Dakhiliya'), ('SH', 'Al Sharqiya'), ('BR', 'Al Buraimi'), ('ZU', 'Al Dhahirah'), ('MW', 'Musandam'), ('WR', 'Al Wusta')], default='MS', max_length=250),
        ),
        migrations.AlterField(
            model_name='motorcycle',
            name='regions',
            field=models.CharField(choices=[('MS', 'Muscat'), ('DH', 'Dhofar'), ('BT', 'Al Batinah'), ('DA', 'Al Dakhiliya'), ('SH', 'Al Sharqiya'), ('BR', 'Al Buraimi'), ('ZU', 'Al Dhahirah'), ('MW', 'Musandam'), ('WR', 'Al Wusta')], default='MS', max_length=250),
        ),
        migrations.AlterField(
            model_name='numberplate',
            name='regions',
            field=models.CharField(choices=[('MS', 'Muscat'), ('DH', 'Dhofar'), ('BT', 'Al Batinah'), ('DA', 'Al Dakhiliya'), ('SH', 'Al Sharqiya'), ('BR', 'Al Buraimi'), ('ZU', 'Al Dhahirah'), ('MW', 'Musandam'), ('WR', 'Al Wusta')], default='MS', max_length=250),
        ),
    ]
