# Generated by Django 5.0.1 on 2025-03-05 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0010_drivingtraining_latitude_drivingtraining_longitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drivingtraining',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='drivingtraining',
            name='longitude',
        ),
        migrations.AlterField(
            model_name='drivingtraining',
            name='regions',
            field=models.CharField(choices=[('MS', 'Muscat'), ('DH', 'Dhofar'), ('BT', 'Batinah'), ('DA', 'Dakhiliyah'), ('SH', 'Sharqiyah'), ('BR', 'Buraimi'), ('ZU', 'Zufar'), ('MW', 'Musandam'), ('WR', 'Wusta')], default='MS', max_length=250),
        ),
    ]
