# Generated by Django 5.1.5 on 2025-03-07 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0012_remove_company_city_company_cities_company_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='cities',
            field=models.TextField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobpost',
            name='regions',
            field=models.TextField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
