# Generated by Django 5.0.1 on 2025-03-08 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0013_jobpost_cities_jobpost_regions'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivingtraining',
            name='latitude',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='drivingtraining',
            name='longitude',
            field=models.FloatField(default=1.0),
        ),
    ]
