# Generated by Django 5.0.1 on 2025-03-08 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0014_drivingtraining_latitude_drivingtraining_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drivingtraining',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='drivingtraining',
            name='longitude',
        ),
    ]
