# Generated by Django 5.1.1 on 2025-03-14 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0016_apartmentlisting'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApartmentListing',
        ),
    ]
