# Generated by Django 5.1.1 on 2025-03-15 05:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0018_villa_rental_period'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Building/images/', verbose_name='Image')),
            ],
        ),
        migrations.CreateModel(
            name='BuildingVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='Building/videos/', verbose_name='Video')),
            ],
        ),
        migrations.CreateModel(
            name='WholeBuilding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_title', models.CharField(max_length=255, verbose_name='Property Title')),
                ('image', models.ImageField(upload_to='wholebuilding/', verbose_name='Main Image')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price (OMR)')),
                ('surface_area', models.FloatField(verbose_name='Surface Area (m²)')),
                ('land_area', models.FloatField(verbose_name='Land Area (m²)')),
                ('number_of_floors', models.IntegerField(verbose_name='Number of Floors')),
                ('building_age', models.IntegerField(verbose_name='Building Age (years)')),
                ('region', models.CharField(choices=[('MS', 'Muscat'), ('DH', 'Dhofar'), ('BT', 'Batinah'), ('DA', 'Dakhiliyah'), ('SH', 'Sharqiyah'), ('BR', 'Buraimi'), ('ZU', 'Zufar'), ('MW', 'Musandam'), ('WR', 'Wusta')], default='MS', max_length=250)),
                ('city', models.CharField(max_length=100)),
                ('nearby_locations', models.TextField(verbose_name='Nearby Locations')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('description', models.TextField(verbose_name='Property Description')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('soldout', 'Soldout')], default='pending', max_length=20, verbose_name='Approval Status')),
                ('listing_type', models.CharField(choices=[('sell', 'Sell'), ('rent', 'Rent')], default='sell', max_length=10, verbose_name='Listing Type')),
                ('rental_period', models.CharField(blank=True, choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=10, null=True, verbose_name='Rental Period')),
                ('lister_type', models.CharField(choices=[('agent', 'Agent'), ('landlord', 'Landlord')], default='agent', max_length=10, verbose_name='Lister Type')),
                ('property_status', models.CharField(choices=[('complete', 'Complete'), ('under_construction', 'Under Construction')], default='complete', max_length=20, verbose_name='Property Status')),
                ('mortgaged', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3, verbose_name='Is the Property Mortgaged?')),
                ('facade', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=10, verbose_name='Does the Property have a Facade?')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('images', models.ManyToManyField(blank=True, related_name='wholebuilding', to='oman_app.buildingimage', verbose_name='Images')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to=settings.AUTH_USER_MODEL)),
                ('videos', models.ManyToManyField(blank=True, related_name='wholebuilding', to='oman_app.buildingvideo', verbose_name='Videos')),
            ],
        ),
    ]
