# Generated by Django 5.1.1 on 2025-03-18 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0020_remove_wholebuilding_images_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='villa',
            name='amenities_additional',
            field=models.JSONField(default=list, verbose_name='Additional Amenities'),
        ),
        migrations.AddField(
            model_name='villa',
            name='amenities_main',
            field=models.JSONField(default=list, verbose_name='Main Amenities'),
        ),
        migrations.AddField(
            model_name='villa',
            name='amenities_nearby',
            field=models.JSONField(default=list, verbose_name='Nearby Amenities'),
        ),
        migrations.AddField(
            model_name='villa',
            name='building_age',
            field=models.CharField(choices=[('under_construction', 'Under Construction'), ('0-11_months', '0-11 Months'), ('1-5_years', '1-5 Years'), ('6-9_years', '6-9 Years'), ('10-19_years', '10-19 Years'), ('20+_years', '20+ Years')], default=1, max_length=20, verbose_name='Building Age'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='villa',
            name='facade',
            field=models.CharField(choices=[('northern', 'Northern'), ('southern', 'Southern')], default=1, max_length=10, verbose_name='Facade'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='villa',
            name='furnished_status',
            field=models.CharField(choices=[('furnished', 'Furnished'), ('semi-furnished', 'Semi-Furnished'), ('unfurnished', 'Unfurnished')], default='unfurnished', max_length=20, verbose_name='Furnished Status'),
        ),
        migrations.AddField(
            model_name='villa',
            name='land_area',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Land Area (sqft)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='villa',
            name='lister_type',
            field=models.CharField(choices=[('agent', 'Agent'), ('landlord', 'Landlord')], default=1, max_length=10, verbose_name='Lister Type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='villa',
            name='number_of_floors',
            field=models.CharField(choices=[('1', '1 Floor'), ('2', '2 Floors'), ('3', '3 Floors'), ('4', '4 Floors'), ('5+', '5+ Floors')], default=1, max_length=10, verbose_name='Number of Floors'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='villa',
            name='property_mortgage',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3, verbose_name='Property Mortgage'),
        ),
    ]
