# Generated by Django 5.1.1 on 2025-03-18 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0021_villa_amenities_additional_villa_amenities_main_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='villa',
            name='amenities_additional',
            field=models.JSONField(blank=True, default=list, verbose_name='Additional Amenities'),
        ),
        migrations.AlterField(
            model_name='villa',
            name='amenities_main',
            field=models.JSONField(blank=True, default=list, verbose_name='Main Amenities'),
        ),
        migrations.AlterField(
            model_name='villa',
            name='amenities_nearby',
            field=models.JSONField(blank=True, default=list, verbose_name='Nearby Amenities'),
        ),
        migrations.AlterField(
            model_name='villa',
            name='cities',
            field=models.CharField(max_length=250, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='villa',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='villas', to='oman_app.villaimage', verbose_name='Additional Images'),
        ),
        migrations.AlterField(
            model_name='villa',
            name='location',
            field=models.CharField(max_length=250, verbose_name='Location Address'),
        ),
        migrations.AlterField(
            model_name='villa',
            name='plot_area',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Plot Area (sqft)'),
        ),
        migrations.AlterField(
            model_name='villa',
            name='videos',
            field=models.ManyToManyField(blank=True, related_name='villas', to='oman_app.villavideo', verbose_name='Property Videos'),
        ),
    ]
