# Generated by Django 5.1.1 on 2025-03-18 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0022_alter_villa_amenities_additional_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='villa',
            name='amenities_additional',
        ),
        migrations.RemoveField(
            model_name='villa',
            name='amenities_main',
        ),
        migrations.RemoveField(
            model_name='villa',
            name='amenities_nearby',
        ),
    ]
