# Generated by Django 5.1.1 on 2025-03-18 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0023_remove_villa_amenities_additional_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='villa',
            name='building_age',
        ),
        migrations.RemoveField(
            model_name='villa',
            name='facade',
        ),
        migrations.RemoveField(
            model_name='villa',
            name='furnished_status',
        ),
        migrations.RemoveField(
            model_name='villa',
            name='land_area',
        ),
        migrations.RemoveField(
            model_name='villa',
            name='lister_type',
        ),
        migrations.RemoveField(
            model_name='villa',
            name='number_of_floors',
        ),
        migrations.RemoveField(
            model_name='villa',
            name='property_mortgage',
        ),
        migrations.AlterField(
            model_name='villa',
            name='cities',
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name='villa',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='villa', to='oman_app.villaimage', verbose_name='Images'),
        ),
        migrations.AlterField(
            model_name='villa',
            name='location',
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name='villa',
            name='plot_area',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Plot Area'),
        ),
        migrations.AlterField(
            model_name='villa',
            name='videos',
            field=models.ManyToManyField(blank=True, related_name='villa', to='oman_app.villavideo', verbose_name='Videos'),
        ),
    ]
