# Generated by Django 5.1.1 on 2025-03-18 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0024_remove_villa_building_age_remove_villa_facade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='villa',
            name='furnished_status',
            field=models.CharField(choices=[('furnished', 'Furnished'), ('semi-furnished', 'Semi-Furnished'), ('unfurnished', 'Unfurnished')], default='unfurnished', max_length=20, verbose_name='Furnished Status'),
        ),
        migrations.AddField(
            model_name='villa',
            name='number_of_floors',
            field=models.CharField(choices=[('1', '1 Floor'), ('2', '2 Floors'), ('3', '3 Floors'), ('4', '4 Floors'), ('5+', '5+ Floors')], default=1, max_length=10, verbose_name='Number of Floors'),
            preserve_default=False,
        ),
    ]
