# Generated by Django 5.1.1 on 2025-03-18 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0025_villa_furnished_status_villa_number_of_floors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='villa',
            name='furnished_status',
        ),
    ]
