# Generated by Django 5.1.1 on 2025-03-18 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0026_remove_villa_furnished_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='villa',
            name='number_of_floors',
        ),
    ]
