# Generated by Django 5.1.1 on 2025-03-18 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0027_remove_villa_number_of_floors'),
    ]

    operations = [
        migrations.AddField(
            model_name='villa',
            name='furnished',
            field=models.CharField(choices=[('furnished', 'Furnished'), ('semi-furnished', 'Semi-Furnished'), ('unfurnished', 'Unfurnished')], default='unfurnished', max_length=20, verbose_name='Furnished'),
        ),
    ]
