# Generated by Django 5.1.1 on 2025-03-18 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0029_villa_land_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='villa',
            name='land_area',
        ),
    ]
