# Generated by Django 5.1.1 on 2025-03-18 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0030_remove_villa_land_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='villa',
            name='building_age',
            field=models.CharField(choices=[('under_construction', 'Under Construction'), ('0-11_months', '0-11 Months'), ('1-5_years', '1-5 Years'), ('6-9_years', '6-9 Years'), ('10-19_years', '10-19 Years'), ('20+_years', '20+ Years')], default=1, max_length=20, verbose_name='Building Age'),
            preserve_default=False,
        ),
    ]
