# Generated by Django 5.1.1 on 2025-03-18 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0031_villa_building_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='villa',
            name='building_age',
        ),
        migrations.AddField(
            model_name='villa',
            name='building',
            field=models.CharField(choices=[('under_construction', 'Under Construction'), ('0-11_months', '0-11 Months'), ('1-5_years', '1-5 Years'), ('6-9_years', '6-9 Years'), ('10-19_years', '10-19 Years'), ('20+_years', '20+ Years')], default='under_construction', max_length=20, verbose_name='Building Age'),
        ),
    ]
