# Generated by Django 5.1.1 on 2025-03-18 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0032_remove_villa_building_age_villa_building'),
    ]

    operations = [
        migrations.AlterField(
            model_name='villa',
            name='furnished',
            field=models.CharField(choices=[('furnished', 'Furnished'), ('semi_furnished', 'Semi-Furnished'), ('unfurnished', 'Unfurnished')], default='unfurnished', max_length=20, verbose_name='Furnished'),
        ),
    ]
