# Generated by Django 5.1.1 on 2025-03-18 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0033_alter_villa_furnished'),
    ]

    operations = [
        migrations.AddField(
            model_name='villa',
            name='floors',
            field=models.CharField(choices=[('1', '1 Floor'), ('2', '2 Floors'), ('3', '3 Floors'), ('4', '4 Floors'), ('5+', '5+ Floors')], default='1', max_length=10, verbose_name='Number of Floors'),
        ),
    ]
