# Generated by Django 5.1.1 on 2025-03-18 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0034_villa_floors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='villa',
            name='building',
            field=models.CharField(choices=[('under_construction', 'Under Construction'), ('0 to 11_months', '0-11 Months'), ('1 to 5_years', '1-5 Years'), ('6 to 9_years', '6-9 Years'), ('10 to 19_years', '10-19 Years'), ('20+_years', '20+ Years')], default='under_construction', max_length=20, verbose_name='Building Age'),
        ),
    ]
