# Generated by Django 5.1.1 on 2025-03-18 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0035_alter_villa_building'),
    ]

    operations = [
        migrations.AlterField(
            model_name='villa',
            name='building',
            field=models.CharField(choices=[('under_construction', 'Under Construction'), ('0_11_months', '0-11 Months'), ('1_5_years', '1-5 Years'), ('6_9_years', '6-9 Years'), ('10_19_years', '10-19 Years'), ('20+_years', '20+ Years')], default='under_construction', max_length=20, verbose_name='Building Age'),
        ),
    ]
