# Generated by Django 5.1.1 on 2025-03-18 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0037_remove_villa_floors_alter_villa_building'),
    ]

    operations = [
        migrations.AddField(
            model_name='villa',
            name='facade',
            field=models.CharField(choices=[('northern', 'Northern'), ('southern', 'Southern')], default=1, max_length=10, verbose_name='Facade'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='villa',
            name='lister_type',
            field=models.CharField(choices=[('agent', 'Agent'), ('landlord', 'Landlord')], default=1, max_length=10, verbose_name='Lister Type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='villa',
            name='property_mortgage',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3, verbose_name='Property Mortgage'),
        ),
    ]
