# Generated by Django 5.1.1 on 2025-03-18 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0038_villa_facade_villa_lister_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='villa',
            name='number',
            field=models.CharField(choices=[('one', '1 Floor'), ('two', '2 Floors'), ('three', '3 Floors'), ('four', '4 Floors'), ('five+', '5+ Floors')], default='one', max_length=10, verbose_name='Number of Floors'),
        ),
    ]
