# Generated by Django 5.1.1 on 2025-03-18 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0039_villa_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='villa',
            name='number',
        ),
    ]
