# Generated by Django 5.1.1 on 2025-03-18 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0040_remove_villa_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='villa',
            name='number_of_floors',
            field=models.PositiveIntegerField(default=1, verbose_name='Number of Floors'),
            preserve_default=False,
        ),
    ]
