# Generated by Django 5.1.1 on 2025-03-19 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0041_villa_number_of_floors'),
    ]

    operations = [
        migrations.AddField(
            model_name='land',
            name='facade',
            field=models.CharField(choices=[('northern', 'Northern'), ('southern', 'Southern')], default=1, max_length=10, verbose_name='Facade'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='land',
            name='lister_type',
            field=models.CharField(choices=[('agent', 'Agent'), ('landlord', 'Landlord')], default=1, max_length=10, verbose_name='Lister Type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='land',
            name='property_mortgage',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3, verbose_name='Property Mortgage'),
        ),
        migrations.AddField(
            model_name='land',
            name='rental_period',
            field=models.CharField(blank=True, choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=10, null=True, verbose_name='Rental Period'),
        ),
    ]
