# Generated by Django 5.1.1 on 2025-03-19 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0043_land_zoned_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='commercial',
            name='furnished',
            field=models.CharField(choices=[('furnished', 'Furnished'), ('semi_furnished', 'Semi-Furnished'), ('unfurnished', 'Unfurnished')], default='unfurnished', max_length=20, verbose_name='Furnished'),
        ),
        migrations.AddField(
            model_name='commercial',
            name='lister_type',
            field=models.CharField(choices=[('agent', 'Agent'), ('landlord', 'Landlord')], default=1, max_length=10, verbose_name='Lister Type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commercial',
            name='number_of_floors',
            field=models.PositiveIntegerField(default=1, verbose_name='Number of Floors'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commercial',
            name='property_mortgage',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3, verbose_name='Property Mortgage'),
        ),
        migrations.AddField(
            model_name='commercial',
            name='property_status',
            field=models.CharField(choices=[('complete', 'Complete'), ('under_construction', 'Under Construction')], default='under_construction', max_length=20, verbose_name='Property Status'),
        ),
        migrations.AddField(
            model_name='commercial',
            name='rental_period',
            field=models.CharField(blank=True, choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=10, null=True, verbose_name='Rental Period'),
        ),
    ]
