# Generated by Django 5.1.1 on 2025-03-19 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0044_commercial_furnished_commercial_lister_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commercial',
            name='property_status',
        ),
    ]
