# Generated by Django 5.1.1 on 2025-03-19 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0045_remove_commercial_property_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commercial',
            name='rental_period',
        ),
        migrations.AddField(
            model_name='commercial',
            name='property',
            field=models.CharField(choices=[('complete', 'Complete'), ('under_construction', 'Under Construction')], default='under_construction', max_length=20, verbose_name='Property Status'),
        ),
    ]
