# Generated by Django 5.1.1 on 2025-03-19 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0046_remove_commercial_rental_period_commercial_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='bathrooms',
            field=models.IntegerField(null=True, verbose_name='Number of Bathrooms'),
        ),
        migrations.AddField(
            model_name='farm',
            name='bedrooms',
            field=models.IntegerField(default=1, verbose_name='Number of Bedrooms'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='farm',
            name='building',
            field=models.CharField(choices=[('under_construction', 'Under Construction'), ('0-11_months', '0-11 Months'), ('1-5_years', '1-5 Years'), ('6-9_years', '6-9 Years'), ('10-19_years', '10-19 Years'), ('20+_years', '20+ Years')], default='under_construction', max_length=20, verbose_name='Building Age'),
        ),
        migrations.AddField(
            model_name='farm',
            name='facade',
            field=models.CharField(choices=[('northern', 'Northern'), ('southern', 'Southern')], default=1, max_length=10, verbose_name='Facade'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='farm',
            name='furnished',
            field=models.CharField(choices=[('furnished', 'Furnished'), ('semi_furnished', 'Semi-Furnished'), ('unfurnished', 'Unfurnished')], default='unfurnished', max_length=20, verbose_name='Furnished'),
        ),
        migrations.AddField(
            model_name='farm',
            name='lister_type',
            field=models.CharField(choices=[('agent', 'Agent'), ('landlord', 'Landlord')], default=1, max_length=10, verbose_name='Lister Type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='farm',
            name='property_mortgage',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3, verbose_name='Property Mortgage'),
        ),
    ]
