# Generated by Django 5.1.1 on 2025-03-19 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0049_factoryimage_factoryvideo_factory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='bathrooms',
            field=models.IntegerField(null=True, verbose_name='Number of Bathrooms'),
        ),
    ]
