# Generated by Django 5.1.1 on 2025-03-19 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0050_alter_apartment_bathrooms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='bedrooms',
            field=models.IntegerField(null=True, verbose_name='Number of Bedrooms'),
        ),
    ]
