# Generated by Django 5.1.1 on 2025-03-19 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0051_alter_apartment_bedrooms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='number_of_floors',
            field=models.PositiveIntegerField(null=True, verbose_name='Number of Floors'),
        ),
    ]
