# Generated by Django 5.1.1 on 2025-03-19 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0053_compleximage_complexvideo_factory_number_of_floors_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complex',
            name='property',
        ),
    ]
