# Generated by Django 5.1.1 on 2025-03-19 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0054_remove_complex_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='complex',
            name='property',
            field=models.CharField(choices=[('complete', 'Complete'), ('under_construction', 'Under Construction')], default='under_construction', max_length=20, verbose_name='Property Status'),
        ),
    ]
