# Generated by Django 5.1.1 on 2025-03-19 09:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0060_cafeimage_cafevideo_cafe'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Staff/images/', verbose_name='Image')),
            ],
        ),
        migrations.CreateModel(
            name='StaffVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='Staff/videos/', verbose_name='Video')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_title', models.CharField(max_length=255, verbose_name='Property Title')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price (OMR)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('bedrooms', models.IntegerField(null=True, verbose_name='Number of Bedrooms')),
                ('regions', models.CharField(choices=[('MS', 'Muscat'), ('DH', 'Dhofar'), ('BT', 'Batinah'), ('DA', 'Dakhiliyah'), ('SH', 'Sharqiyah'), ('BR', 'Buraimi'), ('ZU', 'Zufar'), ('MW', 'Musandam'), ('WR', 'Wusta')], default='MS', max_length=250)),
                ('cities', models.TextField(max_length=250)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('location', models.TextField(max_length=250)),
                ('plot_area', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Plot Area')),
                ('description', models.TextField(verbose_name='Property Description')),
                ('number_of_floors', models.PositiveIntegerField(null=True, verbose_name='Number of Floors')),
                ('listing_type', models.CharField(choices=[('sell', 'Sell'), ('rent', 'Rent')], default='sell', max_length=10, verbose_name='Listing Type')),
                ('furnished', models.CharField(choices=[('furnished', 'Furnished'), ('semi_furnished', 'Semi-Furnished'), ('unfurnished', 'Unfurnished')], default='unfurnished', max_length=20, verbose_name='Furnished')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('soldout', 'Soldout')], default='pending', max_length=20, verbose_name='Approval Status')),
                ('property_mortgage', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3, verbose_name='Property Mortgage')),
                ('lister_type', models.CharField(choices=[('agent', 'Agent'), ('landlord', 'Landlord')], max_length=10, verbose_name='Lister Type')),
                ('property', models.CharField(choices=[('complete', 'Complete'), ('under_construction', 'Under Construction')], default='under_construction', max_length=20, verbose_name='Property Status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Staff', to=settings.AUTH_USER_MODEL)),
                ('images', models.ManyToManyField(blank=True, related_name='Staff', to='oman_app.staffimage', verbose_name='Images')),
                ('videos', models.ManyToManyField(blank=True, related_name='Staff', to='oman_app.staffvideo', verbose_name='Videos')),
            ],
        ),
    ]
