# Generated by Django 5.0.1 on 2025-03-20 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0065_showroomsimage_showroomsvideo_showrooms'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalAmenities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Location Name')),
            ],
        ),
        migrations.CreateModel(
            name='MainAmenities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Location Name')),
            ],
        ),
        migrations.CreateModel(
            name='NearbyLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Location Name')),
            ],
        ),
        migrations.RemoveField(
            model_name='land',
            name='additional_information',
        ),
        migrations.RemoveField(
            model_name='land',
            name='contact_details',
        ),
        migrations.RemoveField(
            model_name='land',
            name='location',
        ),
        migrations.RemoveField(
            model_name='land',
            name='ownership_details',
        ),
        migrations.RemoveField(
            model_name='land',
            name='property_type',
        ),
        migrations.RemoveField(
            model_name='villa',
            name='additional_information',
        ),
        migrations.RemoveField(
            model_name='villa',
            name='contact_details',
        ),
        migrations.RemoveField(
            model_name='villa',
            name='location',
        ),
        migrations.RemoveField(
            model_name='villa',
            name='ownership_details',
        ),
        migrations.RemoveField(
            model_name='villa',
            name='property_type',
        ),
        migrations.AlterField(
            model_name='land',
            name='plot_area',
            field=models.CharField(max_length=100, verbose_name='Land Area'),
        ),
        migrations.AlterField(
            model_name='land',
            name='zoned_for',
            field=models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('farm', 'Farm'), ('industrial', 'Industrial'), ('mixed use', 'Mixed Use')], max_length=100, verbose_name='Zoned For'),
        ),
        migrations.AlterField(
            model_name='villa',
            name='plot_area',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Land Area'),
        ),
        migrations.AddField(
            model_name='villa',
            name='additional_amenities',
            field=models.ManyToManyField(to='oman_app.additionalamenities'),
        ),
        migrations.AddField(
            model_name='villa',
            name='main_amenities',
            field=models.ManyToManyField(to='oman_app.mainamenities'),
        ),
        migrations.AddField(
            model_name='land',
            name='nearby_location',
            field=models.ManyToManyField(to='oman_app.nearbylocation'),
        ),
        migrations.AddField(
            model_name='villa',
            name='nearby_location',
            field=models.ManyToManyField(to='oman_app.nearbylocation'),
        ),
    ]
