# Generated by Django 5.0.1 on 2025-03-20 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0066_additionalamenities_mainamenities_nearbylocation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='land',
            name='facade',
            field=models.CharField(choices=[('northern', 'Northern'), ('southern', 'Southern'), ('eastern', 'Eastern'), ('western', 'Western'), ('northeast', 'Northeast'), ('southeast', 'Southeast'), ('northwest', 'Northwest'), ('southwest', 'Southwest')], max_length=10, verbose_name='Facade'),
        ),
        migrations.AlterField(
            model_name='land',
            name='regions',
            field=models.CharField(choices=[('MS', 'Muscat'), ('DH', 'Dhofar'), ('BT', 'Al Batinah'), ('DA', 'Al Dakhiliya'), ('SH', 'Al Sharqiya'), ('BR', 'Al Buraimi'), ('ZU', 'Al Dhahirah'), ('MW', 'Musandam'), ('WR', 'Al Wusta')], default='MS', max_length=250),
        ),
        migrations.AlterField(
            model_name='villa',
            name='bathrooms',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6+', '6+')], max_length=10, verbose_name='Number of Bathrooms'),
        ),
        migrations.AlterField(
            model_name='villa',
            name='bedrooms',
            field=models.CharField(choices=[('studio', 'Studio'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6+', '6+')], max_length=10, verbose_name='Number of Bedrooms'),
        ),
        migrations.AlterField(
            model_name='villa',
            name='facade',
            field=models.CharField(choices=[('northern', 'Northern'), ('southern', 'Southern'), ('eastern', 'Eastern'), ('western', 'Western'), ('northeast', 'Northeast'), ('southeast', 'Southeast'), ('northwest', 'Northwest'), ('southwest', 'Southwest')], max_length=10, verbose_name='Facade'),
        ),
        migrations.AlterField(
            model_name='villa',
            name='regions',
            field=models.CharField(choices=[('MS', 'Muscat'), ('DH', 'Dhofar'), ('BT', 'Al Batinah'), ('DA', 'Al Dakhiliya'), ('SH', 'Al Sharqiya'), ('BR', 'Al Buraimi'), ('ZU', 'Al Dhahirah'), ('MW', 'Musandam'), ('WR', 'Al Wusta')], default='MS', max_length=250),
        ),
    ]
