# Generated by Django 5.0.1 on 2025-03-20 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0068_alter_villa_number_of_floors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='villa',
            name='number_of_floors',
            field=models.PositiveIntegerField(verbose_name='Number of Floors'),
        ),
    ]
