# Generated by Django 5.0.1 on 2025-03-20 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0071_alter_villa_number_of_floors'),
    ]

    operations = [
        migrations.AddField(
            model_name='villa',
            name='floors',
            field=models.CharField(choices=[('1_floor', '1 Floor'), ('2_floors', '2 Floors'), ('3_floors', '3 Floors'), ('4_floors', '4 Floors'), ('5_floors', '5+ Floors')], default='1', max_length=250),
        ),
    ]
