# Generated by Django 5.0.1 on 2025-03-20 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0072_villa_floors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='villa',
            name='floors',
            field=models.CharField(choices=[('1_floor', '1 Floor'), ('2_floor', '2 Floors'), ('3_floor', '3 Floors'), ('4_floor', '4 Floors'), ('5_floor', '5+ Floors')], default='1_floor', max_length=250),
        ),
    ]
