# Generated by Django 5.0.1 on 2025-03-20 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0073_alter_villa_floors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='villa',
            name='number_of_floors',
        ),
    ]
