# Generated by Django 5.0.1 on 2025-03-20 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0075_villa_surface_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commercial',
            name='additional_information',
        ),
        migrations.RemoveField(
            model_name='commercial',
            name='amenities',
        ),
        migrations.RemoveField(
            model_name='commercial',
            name='contact_details',
        ),
        migrations.RemoveField(
            model_name='commercial',
            name='location',
        ),
        migrations.RemoveField(
            model_name='commercial',
            name='number_of_floors',
        ),
        migrations.RemoveField(
            model_name='commercial',
            name='ownership_details',
        ),
        migrations.RemoveField(
            model_name='commercial',
            name='property_type',
        ),
        migrations.AddField(
            model_name='commercial',
            name='additional_amenities',
            field=models.ManyToManyField(to='oman_app.additionalamenities'),
        ),
        migrations.AddField(
            model_name='commercial',
            name='floors',
            field=models.CharField(choices=[('1_floor', '1 Floor'), ('2_floor', '2 Floors'), ('3_floor', '3 Floors'), ('4_floor', '4 Floors'), ('5_floor', '5+ Floors')], default='1_floor', max_length=250),
        ),
        migrations.AddField(
            model_name='commercial',
            name='main_amenities',
            field=models.ManyToManyField(to='oman_app.mainamenities'),
        ),
        migrations.AddField(
            model_name='commercial',
            name='nearby_location',
            field=models.ManyToManyField(to='oman_app.nearbylocation'),
        ),
        migrations.AlterField(
            model_name='commercial',
            name='plot_area',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Surface Area (sq ft/m²)'),
        ),
    ]
