# Generated by Django 5.0.1 on 2025-03-20 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0076_remove_commercial_additional_information_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farm',
            name='additional_information',
        ),
        migrations.RemoveField(
            model_name='farm',
            name='contact_details',
        ),
        migrations.RemoveField(
            model_name='farm',
            name='irrigation_water_source',
        ),
        migrations.RemoveField(
            model_name='farm',
            name='location',
        ),
        migrations.RemoveField(
            model_name='farm',
            name='soil_type',
        ),
        migrations.RemoveField(
            model_name='farm',
            name='tenancy_information',
        ),
        migrations.AddField(
            model_name='farm',
            name='surface_area',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Surface Area'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apartment',
            name='facade',
            field=models.CharField(choices=[('northern', 'Northern'), ('southern', 'Southern'), ('eastern', 'Eastern'), ('western', 'Western'), ('northeast', 'Northeast'), ('southeast', 'Southeast'), ('northwest', 'Northwest'), ('southwest', 'Southwest')], max_length=10, verbose_name='Facade'),
        ),
        migrations.AlterField(
            model_name='commercial',
            name='regions',
            field=models.CharField(choices=[('MS', 'Muscat'), ('DH', 'Dhofar'), ('BT', 'Al Batinah'), ('DA', 'Al Dakhiliya'), ('SH', 'Al Sharqiya'), ('BR', 'Al Buraimi'), ('ZU', 'Al Dhahirah'), ('MW', 'Musandam'), ('WR', 'Al Wusta')], default='MS', max_length=250),
        ),
        migrations.AlterField(
            model_name='farm',
            name='bathrooms',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6+', '6+')], default=1, max_length=10, verbose_name='Number of Bathrooms'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='farm',
            name='bedrooms',
            field=models.CharField(choices=[('studio', 'Studio'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6+', '6+')], max_length=10, verbose_name='Number of Bedrooms'),
        ),
        migrations.AlterField(
            model_name='farm',
            name='facade',
            field=models.CharField(choices=[('northern', 'Northern'), ('southern', 'Southern'), ('eastern', 'Eastern'), ('western', 'Western'), ('northeast', 'Northeast'), ('southeast', 'Southeast'), ('northwest', 'Northwest'), ('southwest', 'Southwest')], max_length=10, verbose_name='Facade'),
        ),
        migrations.AlterField(
            model_name='farm',
            name='plot_area',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Land Area'),
        ),
        migrations.AlterField(
            model_name='farm',
            name='regions',
            field=models.CharField(choices=[('MS', 'Muscat'), ('DH', 'Dhofar'), ('BT', 'Al Batinah'), ('DA', 'Al Dakhiliya'), ('SH', 'Al Sharqiya'), ('BR', 'Al Buraimi'), ('ZU', 'Al Dhahirah'), ('MW', 'Musandam'), ('WR', 'Al Wusta')], default='MS', max_length=250),
        ),
    ]
