# Generated by Django 5.0.1 on 2025-03-20 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0077_remove_farm_additional_information_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='location',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='number_of_floors',
        ),
        migrations.AddField(
            model_name='apartment',
            name='additional_amenities',
            field=models.ManyToManyField(to='oman_app.additionalamenities'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='floors',
            field=models.CharField(choices=[('1_floor', '1 Floor'), ('2_floor', '2 Floors'), ('3_floor', '3 Floors'), ('4_floor', '4 Floors'), ('5_floor', '5+ Floors')], default='1_floor', max_length=250),
        ),
        migrations.AddField(
            model_name='apartment',
            name='main_amenities',
            field=models.ManyToManyField(to='oman_app.mainamenities'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='nearby_location',
            field=models.ManyToManyField(to='oman_app.nearbylocation'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='bathrooms',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6+', '6+')], default=1, max_length=10, verbose_name='Number of Bathrooms'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apartment',
            name='bedrooms',
            field=models.CharField(choices=[('studio', 'Studio'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6+', '6+')], default=2, max_length=10, verbose_name='Number of Bedrooms'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apartment',
            name='plot_area',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Surface Area'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='regions',
            field=models.CharField(choices=[('MS', 'Muscat'), ('DH', 'Dhofar'), ('BT', 'Al Batinah'), ('DA', 'Al Dakhiliya'), ('SH', 'Al Sharqiya'), ('BR', 'Al Buraimi'), ('ZU', 'Al Dhahirah'), ('MW', 'Musandam'), ('WR', 'Al Wusta')], default='MS', max_length=250),
        ),
    ]
