# Generated by Django 5.0.1 on 2025-03-20 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0078_remove_apartment_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factory',
            name='location',
        ),
        migrations.RemoveField(
            model_name='factory',
            name='number_of_floors',
        ),
        migrations.AddField(
            model_name='factory',
            name='additional_amenities',
            field=models.ManyToManyField(to='oman_app.additionalamenities'),
        ),
        migrations.AddField(
            model_name='factory',
            name='main_amenities',
            field=models.ManyToManyField(to='oman_app.mainamenities'),
        ),
        migrations.AddField(
            model_name='factory',
            name='nearby_location',
            field=models.ManyToManyField(to='oman_app.nearbylocation'),
        ),
        migrations.AlterField(
            model_name='factory',
            name='plot_area',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Surface Area'),
        ),
        migrations.AlterField(
            model_name='factory',
            name='regions',
            field=models.CharField(choices=[('MS', 'Muscat'), ('DH', 'Dhofar'), ('BT', 'Al Batinah'), ('DA', 'Al Dakhiliya'), ('SH', 'Al Sharqiya'), ('BR', 'Al Buraimi'), ('ZU', 'Al Dhahirah'), ('MW', 'Musandam'), ('WR', 'Al Wusta')], default='MS', max_length=250),
        ),
    ]
