# Generated by Django 5.0.1 on 2025-03-21 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0080_remove_complex_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinic',
            name='location',
        ),
        migrations.RemoveField(
            model_name='clinic',
            name='number_of_floors',
        ),
        migrations.AddField(
            model_name='clinic',
            name='additional_amenities',
            field=models.ManyToManyField(to='oman_app.additionalamenities'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='floors',
            field=models.CharField(choices=[('basement_floor', 'Basement Floor'), ('semiground_floor', 'Semiground Floor'), ('grounded_floor', 'Grounded Floor'), ('1_floor', '1 Floor'), ('2_floor', '2 Floors'), ('3_floor', '3 Floors'), ('4_floor', '4 Floors'), ('5_floor', '5 Floors'), ('6_floor', '6 Floors'), ('7_floor', '7 Floors'), ('8_floor', '8 Floors'), ('lastfloorwith_roof', 'Last floor with roof')], default='1_floor', max_length=250),
        ),
        migrations.AddField(
            model_name='clinic',
            name='main_amenities',
            field=models.ManyToManyField(to='oman_app.mainamenities'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='nearby_location',
            field=models.ManyToManyField(to='oman_app.nearbylocation'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='plot_area',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Surface Area'),
        ),
    ]
