# Generated by Django 5.0.1 on 2025-03-21 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0081_remove_clinic_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinic',
            name='floors',
        ),
    ]
