# Generated by Django 5.0.1 on 2025-03-21 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0084_remove_hostel_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='office',
            name='location',
        ),
        migrations.RemoveField(
            model_name='office',
            name='number_of_floors',
        ),
        migrations.AddField(
            model_name='office',
            name='additional_amenities',
            field=models.ManyToManyField(to='oman_app.additionalamenities'),
        ),
        migrations.AddField(
            model_name='office',
            name='floors',
            field=models.CharField(choices=[('basement_floor', 'Basement Floor'), ('semiground_floor', 'Semi Ground Floor'), ('ground_floor', 'Ground Floor'), ('1_floor', '1 Floor'), ('2_floor', '2 Floors'), ('3_floor', '3 Floors'), ('4_floor', '4 Floors'), ('5_floor', '5 Floors'), ('6_floor', '6 Floors'), ('7_floor', '7 Floors'), ('8_floor', '8 Floors'), ('lastfloorwith_roof', 'Last Floor with Roof')], default='1_floor', max_length=250),
        ),
        migrations.AddField(
            model_name='office',
            name='furnished',
            field=models.CharField(choices=[('furnished', 'Furnished'), ('semi_furnished', 'Semi-Furnished'), ('unfurnished', 'Unfurnished')], default='unfurnished', max_length=20, verbose_name='Furnished'),
        ),
        migrations.AddField(
            model_name='office',
            name='main_amenities',
            field=models.ManyToManyField(to='oman_app.mainamenities'),
        ),
        migrations.AddField(
            model_name='office',
            name='nearby_location',
            field=models.ManyToManyField(to='oman_app.nearbylocation'),
        ),
        migrations.AlterField(
            model_name='office',
            name='plot_area',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Surface Area'),
        ),
    ]
