# Generated by Django 5.0.1 on 2025-03-21 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0086_remove_shop_location_shop_additional_amenities_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cafe',
            name='location',
        ),
        migrations.AddField(
            model_name='cafe',
            name='additional_amenities',
            field=models.ManyToManyField(to='oman_app.additionalamenities'),
        ),
        migrations.AddField(
            model_name='cafe',
            name='main_amenities',
            field=models.ManyToManyField(to='oman_app.mainamenities'),
        ),
        migrations.AddField(
            model_name='cafe',
            name='nearby_location',
            field=models.ManyToManyField(to='oman_app.nearbylocation'),
        ),
        migrations.AddField(
            model_name='fullfloors',
            name='additional_amenities',
            field=models.ManyToManyField(to='oman_app.additionalamenities'),
        ),
        migrations.AddField(
            model_name='fullfloors',
            name='main_amenities',
            field=models.ManyToManyField(to='oman_app.mainamenities'),
        ),
        migrations.AddField(
            model_name='fullfloors',
            name='nearby_location',
            field=models.ManyToManyField(to='oman_app.nearbylocation'),
        ),
        migrations.AddField(
            model_name='showrooms',
            name='additional_amenities',
            field=models.ManyToManyField(to='oman_app.additionalamenities'),
        ),
        migrations.AddField(
            model_name='showrooms',
            name='main_amenities',
            field=models.ManyToManyField(to='oman_app.mainamenities'),
        ),
        migrations.AddField(
            model_name='showrooms',
            name='nearby_location',
            field=models.ManyToManyField(to='oman_app.nearbylocation'),
        ),
        migrations.AddField(
            model_name='staff',
            name='additional_amenities',
            field=models.ManyToManyField(to='oman_app.additionalamenities'),
        ),
        migrations.AddField(
            model_name='staff',
            name='main_amenities',
            field=models.ManyToManyField(to='oman_app.mainamenities'),
        ),
        migrations.AddField(
            model_name='staff',
            name='nearby_location',
            field=models.ManyToManyField(to='oman_app.nearbylocation'),
        ),
        migrations.AddField(
            model_name='townhouse',
            name='additional_amenities',
            field=models.ManyToManyField(to='oman_app.additionalamenities'),
        ),
        migrations.AddField(
            model_name='townhouse',
            name='main_amenities',
            field=models.ManyToManyField(to='oman_app.mainamenities'),
        ),
        migrations.AddField(
            model_name='townhouse',
            name='nearby_location',
            field=models.ManyToManyField(to='oman_app.nearbylocation'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='additional_amenities',
            field=models.ManyToManyField(to='oman_app.additionalamenities'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='main_amenities',
            field=models.ManyToManyField(to='oman_app.mainamenities'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='nearby_location',
            field=models.ManyToManyField(to='oman_app.nearbylocation'),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='plot_area',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Surface Area'),
        ),
    ]
