# Generated by Django 5.0.1 on 2025-03-21 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0087_remove_cafe_location_cafe_additional_amenities_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='location',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='number_of_floors',
        ),
        migrations.AddField(
            model_name='staff',
            name='floors',
            field=models.CharField(choices=[('1_floor', '1 Floor'), ('2_floor', '2 Floors'), ('3_floor', '3 Floors'), ('4_floor', '4 Floors'), ('5_floor', '5+ Floors')], default='1_floor', max_length=250),
        ),
        migrations.AlterField(
            model_name='staff',
            name='bedrooms',
            field=models.CharField(choices=[('studio', 'Studio'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6+', '6+')], max_length=10, verbose_name='Number of Bedrooms'),
        ),
    ]
