# Generated by Django 5.0.1 on 2025-03-21 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0088_remove_staff_location_remove_staff_number_of_floors_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouse',
            name='location',
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='plot_area',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Surface Area'),
        ),
    ]
