# Generated by Django 5.0.1 on 2025-03-21 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0089_remove_warehouse_location_alter_warehouse_plot_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fullfloors',
            name='number_of_floors',
        ),
        migrations.RemoveField(
            model_name='townhouse',
            name='location',
        ),
        migrations.RemoveField(
            model_name='townhouse',
            name='number_of_floors',
        ),
        migrations.AddField(
            model_name='fullfloors',
            name='floors',
            field=models.CharField(choices=[('1_floor', '1 Floor'), ('2_floor', '2 Floors'), ('3_floor', '3 Floors'), ('4_floor', '4 Floors'), ('5_floor', '5+ Floors')], default='1_floor', max_length=250),
        ),
        migrations.AddField(
            model_name='townhouse',
            name='floors',
            field=models.CharField(choices=[('1_floor', '1 Floor'), ('2_floor', '2 Floors'), ('3_floor', '3 Floors'), ('4_floor', '4 Floors'), ('5_floor', '5+ Floors')], default='1_floor', max_length=250),
        ),
        migrations.AddField(
            model_name='townhouse',
            name='surface_area',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Surface Area'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cafe',
            name='regions',
            field=models.CharField(choices=[('MS', 'Muscat'), ('DH', 'Dhofar'), ('BT', 'Al Batinah'), ('DA', 'Al Dakhiliya'), ('SH', 'Al Sharqiya'), ('BR', 'Al Buraimi'), ('ZU', 'Al Dhahirah'), ('MW', 'Musandam'), ('WR', 'Al Wusta')], default='MS', max_length=250),
        ),
        migrations.AlterField(
            model_name='fullfloors',
            name='regions',
            field=models.CharField(choices=[('MS', 'Muscat'), ('DH', 'Dhofar'), ('BT', 'Al Batinah'), ('DA', 'Al Dakhiliya'), ('SH', 'Al Sharqiya'), ('BR', 'Al Buraimi'), ('ZU', 'Al Dhahirah'), ('MW', 'Musandam'), ('WR', 'Al Wusta')], default='MS', max_length=250),
        ),
        migrations.AlterField(
            model_name='showrooms',
            name='regions',
            field=models.CharField(choices=[('MS', 'Muscat'), ('DH', 'Dhofar'), ('BT', 'Al Batinah'), ('DA', 'Al Dakhiliya'), ('SH', 'Al Sharqiya'), ('BR', 'Al Buraimi'), ('ZU', 'Al Dhahirah'), ('MW', 'Musandam'), ('WR', 'Al Wusta')], default='MS', max_length=250),
        ),
        migrations.AlterField(
            model_name='staff',
            name='regions',
            field=models.CharField(choices=[('MS', 'Muscat'), ('DH', 'Dhofar'), ('BT', 'Al Batinah'), ('DA', 'Al Dakhiliya'), ('SH', 'Al Sharqiya'), ('BR', 'Al Buraimi'), ('ZU', 'Al Dhahirah'), ('MW', 'Musandam'), ('WR', 'Al Wusta')], default='MS', max_length=250),
        ),
        migrations.AlterField(
            model_name='townhouse',
            name='bathrooms',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6+', '6+')], max_length=10, verbose_name='Number of Bathrooms'),
        ),
        migrations.AlterField(
            model_name='townhouse',
            name='bedrooms',
            field=models.CharField(choices=[('studio', 'Studio'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6+', '6+')], max_length=10, verbose_name='Number of Bedrooms'),
        ),
        migrations.AlterField(
            model_name='townhouse',
            name='facade',
            field=models.CharField(choices=[('northern', 'Northern'), ('southern', 'Southern'), ('eastern', 'Eastern'), ('western', 'Western'), ('northeast', 'Northeast'), ('southeast', 'Southeast'), ('northwest', 'Northwest'), ('southwest', 'Southwest')], max_length=10, verbose_name='Facade'),
        ),
        migrations.AlterField(
            model_name='townhouse',
            name='plot_area',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Land Area'),
        ),
        migrations.AlterField(
            model_name='townhouse',
            name='regions',
            field=models.CharField(choices=[('MS', 'Muscat'), ('DH', 'Dhofar'), ('BT', 'Al Batinah'), ('DA', 'Al Dakhiliya'), ('SH', 'Al Sharqiya'), ('BR', 'Al Buraimi'), ('ZU', 'Al Dhahirah'), ('MW', 'Musandam'), ('WR', 'Al Wusta')], default='MS', max_length=250),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='regions',
            field=models.CharField(choices=[('MS', 'Muscat'), ('DH', 'Dhofar'), ('BT', 'Al Batinah'), ('DA', 'Al Dakhiliya'), ('SH', 'Al Sharqiya'), ('BR', 'Al Buraimi'), ('ZU', 'Al Dhahirah'), ('MW', 'Musandam'), ('WR', 'Al Wusta')], default='MS', max_length=250),
        ),
    ]
