# Generated by Django 5.0.1 on 2025-03-21 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0090_remove_fullfloors_number_of_floors_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fullfloors',
            name='location',
        ),
        migrations.AlterField(
            model_name='fullfloors',
            name='floors',
            field=models.CharField(choices=[('basement_floor', 'Basement Floor'), ('semiground_floor', 'Semi Ground Floor'), ('ground_floor', 'Ground Floor'), ('1_floor', '1 Floor'), ('2_floor', '2 Floors'), ('3_floor', '3 Floors'), ('4_floor', '4 Floors'), ('5_floor', '5 Floors'), ('6_floor', '6 Floors'), ('7_floor', '7 Floors'), ('8_floor', '8 Floors'), ('lastfloorwith_roof', 'Last Floor with Roof')], default='1_floor', max_length=250),
        ),
        migrations.AlterField(
            model_name='fullfloors',
            name='plot_area',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Surface Area'),
        ),
    ]
