# Generated by Django 5.0.1 on 2025-03-21 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0091_remove_fullfloors_location_alter_fullfloors_floors_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='showrooms',
            name='location',
        ),
        migrations.AlterField(
            model_name='showrooms',
            name='plot_area',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Surface Area'),
        ),
    ]
