# Generated by Django 5.0.1 on 2025-03-21 16:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0092_remove_showrooms_location_alter_showrooms_plot_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForeignImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Foreign/images/', verbose_name='Image')),
            ],
        ),
        migrations.CreateModel(
            name='ForeignVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='Foreign/videos/', verbose_name='Video')),
            ],
        ),
        migrations.CreateModel(
            name='SupermarketImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Supermarket/images/', verbose_name='Image')),
            ],
        ),
        migrations.CreateModel(
            name='SupermarketVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='Supermarket/videos/', verbose_name='Video')),
            ],
        ),
        migrations.CreateModel(
            name='WholebuildingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Wholebuilding/images/', verbose_name='Image')),
            ],
        ),
        migrations.CreateModel(
            name='WholebuildingVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='Wholebuilding/videos/', verbose_name='Video')),
            ],
        ),
        migrations.CreateModel(
            name='Foreign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_title', models.CharField(max_length=255, verbose_name='Property Title')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price (OMR)')),
                ('regions', models.CharField(choices=[('MS', 'Muscat'), ('DH', 'Dhofar'), ('BT', 'Batinah'), ('DA', 'Dakhiliyah'), ('SH', 'Sharqiyah'), ('BR', 'Buraimi'), ('ZU', 'Zufar'), ('MW', 'Musandam'), ('WR', 'Wusta')], default='MS', max_length=250)),
                ('cities', models.TextField(max_length=250)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('location', models.TextField(max_length=250)),
                ('description', models.TextField(verbose_name='Property Description')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('soldout', 'Soldout')], default='pending', max_length=20, verbose_name='Approval Status')),
                ('listing_type', models.CharField(choices=[('sell', 'Sell'), ('rent', 'Rent')], default='sell', max_length=10, verbose_name='Listing Type')),
                ('lister_type', models.CharField(choices=[('agent', 'Agent'), ('landlord', 'Landlord')], max_length=10, verbose_name='Lister Type')),
                ('estate_type', models.CharField(choices=[('apartment', 'Apartment'), ('chalets', 'Chalets - Summer Houses'), ('commercial', 'Commercial'), ('farm', 'Farm'), ('land', 'Land'), ('villa', 'Villa House')], default='apartment', max_length=20, verbose_name='Estate Type')),
                ('property_mortgage', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3, verbose_name='Property Mortgage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Foreign', to=settings.AUTH_USER_MODEL)),
                ('images', models.ManyToManyField(blank=True, related_name='Foreign', to='oman_app.foreignimage', verbose_name='Images')),
                ('videos', models.ManyToManyField(blank=True, related_name='Foreign', to='oman_app.foreignvideo', verbose_name='Videos')),
            ],
        ),
        migrations.CreateModel(
            name='Supermarket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_title', models.CharField(max_length=255, verbose_name='Property Title')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price (OMR)')),
                ('regions', models.CharField(choices=[('MS', 'Muscat'), ('DH', 'Dhofar'), ('BT', 'Batinah'), ('DA', 'Dakhiliyah'), ('SH', 'Sharqiyah'), ('BR', 'Buraimi'), ('ZU', 'Zufar'), ('MW', 'Musandam'), ('WR', 'Wusta')], default='MS', max_length=250)),
                ('cities', models.TextField(max_length=250)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('location', models.TextField(max_length=250)),
                ('plot_area', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Plot Area')),
                ('description', models.TextField(verbose_name='Property Description')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('soldout', 'Soldout')], default='pending', max_length=20, verbose_name='Approval Status')),
                ('listing_type', models.CharField(choices=[('sell', 'Sell'), ('rent', 'Rent')], default='sell', max_length=10, verbose_name='Listing Type')),
                ('lister_type', models.CharField(choices=[('agent', 'Agent'), ('landlord', 'Landlord')], max_length=10, verbose_name='Lister Type')),
                ('property', models.CharField(choices=[('complete', 'Complete'), ('under_construction', 'Under Construction')], default='under_construction', max_length=20, verbose_name='Property Status')),
                ('property_mortgage', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3, verbose_name='Property Mortgage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Supermarket', to=settings.AUTH_USER_MODEL)),
                ('images', models.ManyToManyField(blank=True, related_name='Supermarket', to='oman_app.supermarketimage', verbose_name='Images')),
                ('videos', models.ManyToManyField(blank=True, related_name='Supermarket', to='oman_app.supermarketvideo', verbose_name='Videos')),
            ],
        ),
        migrations.CreateModel(
            name='Wholebuilding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_title', models.CharField(max_length=255, verbose_name='Property Title')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price (OMR)')),
                ('regions', models.CharField(choices=[('MS', 'Muscat'), ('DH', 'Dhofar'), ('BT', 'Batinah'), ('DA', 'Dakhiliyah'), ('SH', 'Sharqiyah'), ('BR', 'Buraimi'), ('ZU', 'Zufar'), ('MW', 'Musandam'), ('WR', 'Wusta')], default='MS', max_length=250)),
                ('cities', models.TextField(max_length=250)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('location', models.TextField(max_length=250)),
                ('plot_area', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Plot Area')),
                ('number_of_floors', models.PositiveIntegerField(verbose_name='Number of Floors')),
                ('description', models.TextField(verbose_name='Property Description')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('soldout', 'Soldout')], default='pending', max_length=20, verbose_name='Approval Status')),
                ('listing_type', models.CharField(choices=[('sell', 'Sell'), ('rent', 'Rent')], default='sell', max_length=10, verbose_name='Listing Type')),
                ('lister_type', models.CharField(choices=[('agent', 'Agent'), ('landlord', 'Landlord')], max_length=10, verbose_name='Lister Type')),
                ('property', models.CharField(choices=[('complete', 'Complete'), ('under_construction', 'Under Construction')], default='under_construction', max_length=20, verbose_name='Property Status')),
                ('building', models.CharField(choices=[('under_construction', 'Under Construction'), ('0-11_months', '0-11 Months'), ('1-5_years', '1-5 Years'), ('6-9_years', '6-9 Years'), ('10-19_years', '10-19 Years'), ('20+_years', '20+ Years')], default='under_construction', max_length=20, verbose_name='Building Age')),
                ('property_mortgage', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3, verbose_name='Property Mortgage')),
                ('facade', models.CharField(choices=[('northern', 'Northern'), ('southern', 'Southern')], max_length=10, verbose_name='Facade')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Wholebuilding', to=settings.AUTH_USER_MODEL)),
                ('images', models.ManyToManyField(blank=True, related_name='Wholebuilding', to='oman_app.wholebuildingimage', verbose_name='Images')),
                ('videos', models.ManyToManyField(blank=True, related_name='Wholebuilding', to='oman_app.wholebuildingvideo', verbose_name='Videos')),
            ],
        ),
    ]
