# Generated by Django 5.0.1 on 2025-03-21 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0093_foreignimage_foreignvideo_supermarketimage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wholebuilding',
            name='location',
        ),
        migrations.RemoveField(
            model_name='wholebuilding',
            name='number_of_floors',
        ),
        migrations.AddField(
            model_name='wholebuilding',
            name='floors',
            field=models.CharField(choices=[('1_floor', '1 Floor'), ('2_floor', '2 Floors'), ('3_floor', '3 Floors'), ('4_floor', '4 Floors'), ('5_floor', '5+ Floors')], default='1_floor', max_length=250),
        ),
        migrations.AddField(
            model_name='wholebuilding',
            name='nearby_location',
            field=models.ManyToManyField(to='oman_app.nearbylocation'),
        ),
        migrations.AddField(
            model_name='wholebuilding',
            name='surface_area',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Surface Area'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='foreign',
            name='regions',
            field=models.CharField(choices=[('MS', 'Muscat'), ('DH', 'Dhofar'), ('BT', 'Al Batinah'), ('DA', 'Al Dakhiliya'), ('SH', 'Al Sharqiya'), ('BR', 'Al Buraimi'), ('ZU', 'Al Dhahirah'), ('MW', 'Musandam'), ('WR', 'Al Wusta')], default='MS', max_length=250),
        ),
        migrations.AlterField(
            model_name='supermarket',
            name='regions',
            field=models.CharField(choices=[('MS', 'Muscat'), ('DH', 'Dhofar'), ('BT', 'Al Batinah'), ('DA', 'Al Dakhiliya'), ('SH', 'Al Sharqiya'), ('BR', 'Al Buraimi'), ('ZU', 'Al Dhahirah'), ('MW', 'Musandam'), ('WR', 'Al Wusta')], default='MS', max_length=250),
        ),
        migrations.AlterField(
            model_name='wholebuilding',
            name='facade',
            field=models.CharField(choices=[('northern', 'Northern'), ('southern', 'Southern'), ('eastern', 'Eastern'), ('western', 'Western'), ('northeast', 'Northeast'), ('southeast', 'Southeast'), ('northwest', 'Northwest'), ('southwest', 'Southwest')], max_length=10, verbose_name='Facade'),
        ),
        migrations.AlterField(
            model_name='wholebuilding',
            name='plot_area',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Land Area'),
        ),
        migrations.AlterField(
            model_name='wholebuilding',
            name='regions',
            field=models.CharField(choices=[('MS', 'Muscat'), ('DH', 'Dhofar'), ('BT', 'Al Batinah'), ('DA', 'Al Dakhiliya'), ('SH', 'Al Sharqiya'), ('BR', 'Al Buraimi'), ('ZU', 'Al Dhahirah'), ('MW', 'Musandam'), ('WR', 'Al Wusta')], default='MS', max_length=250),
        ),
    ]
