# Generated by Django 5.0.1 on 2025-03-21 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0095_remove_supermarket_location_foreign_nearby_location_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foreign',
            old_name='location',
            new_name='country',
        ),
    ]
