# Generated by Django 5.1.1 on 2025-03-22 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0097_commercial_rental_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='rental_period',
            field=models.CharField(blank=True, choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=10, null=True, verbose_name='Rental\xa0Period'),
        ),
    ]
