# Generated by Django 5.0.1 on 2025-03-28 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0101_farm_additional_amenities_farm_main_amenities_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='furnished',
            field=models.CharField(choices=[('furnished', 'Furnished'), ('semi_furnished', 'Semi-Furnished'), ('unfurnished', 'Unfurnished')], default='unfurnished', max_length=20, verbose_name='Furnished'),
        ),
    ]
