# Generated by Django 5.0.1 on 2025-03-28 09:46

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0102_clinic_furnished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foreign',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
