# Generated by Django 5.1.1 on 2025-03-31 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0104_sharedimage_sharedvideo_shared'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shared',
            name='listing_type',
            field=models.CharField(choices=[('rent', 'Rent')], default='rent', max_length=10, verbose_name='Listing Type'),
        ),
    ]
