# Generated by Django 5.1.1 on 2025-03-31 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0105_alter_shared_listing_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shared',
            name='rental_period',
            field=models.CharField(blank=True, choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=10, null=True, verbose_name='Rental Period'),
        ),
    ]
