# Generated by Django 5.1.1 on 2025-04-02 07:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0107_suitsimage_suitsvideo_suits'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarPartImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='CarPart/images/', verbose_name='Image')),
            ],
        ),
        migrations.CreateModel(
            name='CarPartVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='CarPart/videos/', verbose_name='Video')),
            ],
        ),
        migrations.CreateModel(
            name='CarPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(verbose_name='Description')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price (OMR)')),
                ('regions', models.CharField(choices=[('MS', 'Muscat'), ('DH', 'Dhofar'), ('BT', 'Al Batinah'), ('DA', 'Al Dakhiliya'), ('SH', 'Al Sharqiya'), ('BR', 'Al Buraimi'), ('ZU', 'Al Dhahirah'), ('MW', 'Musandam'), ('WR', 'Al Wusta')], default='MS', max_length=250)),
                ('cities', models.TextField(max_length=250)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('provide_delivery', models.BooleanField(default=False)),
                ('condition', models.CharField(choices=[('batteries', 'Batteries'), ('bodyparts', 'Body Parts'), ('mechanical', 'Mechanical Parts'), ('spareparts', 'Spare Parts'), ('other', 'Other')], max_length=20)),
                ('subtype', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('soldout', 'Soldout')], default='pending', max_length=20, verbose_name='Approval Status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CarPart', to=settings.AUTH_USER_MODEL)),
                ('images', models.ManyToManyField(blank=True, related_name='CarPart', to='oman_app.carpartimage', verbose_name='Images')),
                ('videos', models.ManyToManyField(blank=True, related_name='CarPart', to='oman_app.carpartvideo', verbose_name='Videos')),
            ],
        ),
    ]
