# Generated by Django 5.1.1 on 2025-04-02 07:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0108_carpartimage_carpartvideo_carpart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carpart',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='Carpart', to='oman_app.carpartimage', verbose_name='Images'),
        ),
        migrations.AlterField(
            model_name='carpart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Carpart', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='carpart',
            name='videos',
            field=models.ManyToManyField(blank=True, related_name='Carpart', to='oman_app.carpartvideo', verbose_name='Videos'),
        ),
    ]
