# Generated by Django 5.1.1 on 2025-04-02 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0109_alter_carpart_images_alter_carpart_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carpart',
            name='condition',
            field=models.CharField(choices=[('used', 'Used'), ('like_new', 'Like New')], max_length=10, verbose_name='Condition'),
        ),
        migrations.AlterField(
            model_name='carpartimage',
            name='image',
            field=models.ImageField(upload_to='Carpart/images/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='carpartvideo',
            name='video',
            field=models.FileField(upload_to='Carpart/videos/', verbose_name='Video'),
        ),
    ]
