# Generated by Django 5.1.1 on 2025-04-02 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0110_alter_carpart_condition_alter_carpartimage_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carpart',
            name='provide_delivery',
        ),
        migrations.AddField(
            model_name='carpart',
            name='provide',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3, verbose_name='Delivery'),
        ),
    ]
