# Generated by Django 5.1.1 on 2025-04-02 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0111_remove_carpart_provide_delivery_carpart_provide'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autoaccessorypart',
            name='listing_type',
        ),
        migrations.AddField(
            model_name='heavyvehicle',
            name='type1',
            field=models.CharField(choices=[('ALARM', 'Alarm System'), ('CAMERA', 'Cameras & Sensors'), ('CLEANING', 'Cleaning Tools and Fresheners'), ('FLOORS', 'Floors and Covers'), ('GPS', 'GPS'), ('KEYS', 'Keys'), ('PHONE', 'Phone Holders and Accessories'), ('RECORDER', 'Recorders'), ('SCREEN', 'Screens'), ('SOUND', 'Sound System'), ('SPARK', 'Spark Plug'), ('SPEAKER', 'Speakers'), ('WINDOW', 'Window Tint-Stickers'), ('WIPER', 'Windshield Wipers'), ('OTHER', 'Other')], default=1, max_length=20, verbose_name='Accessory Type'),
            preserve_default=False,
        ),
    ]
