# Generated by Django 5.1.1 on 2025-04-02 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0112_remove_autoaccessorypart_listing_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heavyvehicle',
            name='type1',
        ),
    ]
