# Generated by Django 5.1.1 on 2025-04-02 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0114_autoaccessorypart_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoaccessorypart',
            name='condition',
            field=models.CharField(choices=[('used', 'Used'), ('like_new', 'Like New')], default=1, max_length=10, verbose_name='Condition'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='autoaccessorypart',
            name='provide',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3, verbose_name='Delivery'),
        ),
    ]
