# Generated by Django 5.1.1 on 2025-04-02 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0115_autoaccessorypart_condition_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boat',
            name='engine_power',
        ),
        migrations.RemoveField(
            model_name='boat',
            name='engine_type',
        ),
        migrations.RemoveField(
            model_name='boat',
            name='fuel_type',
        ),
        migrations.RemoveField(
            model_name='boat',
            name='length',
        ),
        migrations.RemoveField(
            model_name='boat',
            name='location',
        ),
        migrations.RemoveField(
            model_name='boat',
            name='year',
        ),
    ]
