# Generated by Django 5.1.1 on 2025-04-10 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0116_remove_boat_engine_power_remove_boat_engine_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='automobile',
            name='number_of_seats',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Number of Seats'),
        ),
        migrations.AddField(
            model_name='automobile',
            name='regional_spec',
            field=models.CharField(choices=[('gcc', 'GCC Spec'), ('euro', 'European Spec'), ('usa', 'USA Spec'), ('japan', 'Japanese Spec'), ('other', 'Other')], default='gcc', max_length=20, verbose_name='Regional Specification'),
        ),
        migrations.AddField(
            model_name='automobile',
            name='rental_period',
            field=models.CharField(blank=True, choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=10, null=True, verbose_name='Rental\xa0Period'),
        ),
        migrations.AddField(
            model_name='automobile',
            name='vin_chassis_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='VIN/Chassis Number'),
        ),
        migrations.AlterField(
            model_name='automobile',
            name='condition',
            field=models.CharField(choices=[('new', 'New'), ('used', 'Used'), ('import', 'Import')], max_length=10, verbose_name='Condition'),
        ),
    ]
