# Generated by Django 5.1.1 on 2025-04-10 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0117_automobile_number_of_seats_automobile_regional_spec_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autoaccessorypart',
            name='location',
        ),
    ]
