# Generated by Django 5.1.1 on 2025-04-10 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0118_remove_autoaccessorypart_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heavyvehicle',
            name='engine_capacity',
        ),
        migrations.RemoveField(
            model_name='heavyvehicle',
            name='fuel_type',
        ),
        migrations.RemoveField(
            model_name='heavyvehicle',
            name='load_capacity',
        ),
        migrations.RemoveField(
            model_name='heavyvehicle',
            name='location',
        ),
        migrations.RemoveField(
            model_name='heavyvehicle',
            name='mileage',
        ),
        migrations.AddField(
            model_name='heavyvehicle',
            name='make',
            field=models.CharField(default=1, max_length=100, verbose_name='Make'),
            preserve_default=False,
        ),
    ]
