# Generated by Django 5.1.1 on 2025-04-10 06:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0119_remove_heavyvehicle_engine_capacity_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CarPartImage',
            new_name='PartImage',
        ),
        migrations.RenameModel(
            old_name='CarPartVideo',
            new_name='PartVideo',
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(choices=[('used', 'Used'), ('like_new', 'Like New')], max_length=10, verbose_name='Condition')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price (OMR)')),
                ('types', models.CharField(choices=[('batteries', 'Batteries'), ('bodyparts', 'Body Parts'), ('mechanical', 'Mechanical Parts'), ('spareparts', 'Spare Parts'), ('other', 'Other')], default='other', max_length=20)),
                ('subtype', models.CharField(max_length=20)),
                ('regions', models.CharField(choices=[('MS', 'Muscat'), ('DH', 'Dhofar'), ('BT', 'Al Batinah'), ('DA', 'Al Dakhiliya'), ('SH', 'Al Sharqiya'), ('BR', 'Al Buraimi'), ('ZU', 'Al Dhahirah'), ('MW', 'Musandam'), ('WR', 'Al Wusta')], default='MS', max_length=250)),
                ('cities', models.TextField(max_length=250)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('description', models.TextField(verbose_name='Description')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('soldout', 'Soldout')], default='pending', max_length=20, verbose_name='Approval Status')),
                ('provide', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3, verbose_name='Delivery')),
                ('images', models.ManyToManyField(blank=True, related_name='Part', to='oman_app.partimage', verbose_name='Images')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Part', to=settings.AUTH_USER_MODEL)),
                ('videos', models.ManyToManyField(blank=True, related_name='Part', to='oman_app.partvideo', verbose_name='Videos')),
            ],
        ),
        migrations.DeleteModel(
            name='CarPart',
        ),
    ]
