# Generated by Django 5.1.1 on 2025-04-10 09:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0120_rename_carpartimage_partimage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LuxuryVehicleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='luxury_vehicles/images/', verbose_name='Image')),
            ],
        ),
        migrations.CreateModel(
            name='LuxuryVehicleVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='luxury_vehicles/videos/', verbose_name='Video')),
            ],
        ),
        migrations.CreateModel(
            name='LuxuryVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bodytype', models.CharField(choices=[('coupe', 'Coupe'), ('convertible', 'Convertible'), ('targa', 'Targa'), ('roadster', 'Roadster'), ('supercar', 'Supercar'), ('hypercar', 'Hypercar'), ('track', 'Track Car'), ('gt', 'Grand Tourer')], max_length=100, verbose_name='Vehicle Body Type')),
                ('top_speed', models.PositiveIntegerField(blank=True, null=True, verbose_name='Top Speed')),
                ('top_speed_unit', models.CharField(choices=[('kmh', 'km/h'), ('mph', 'mph')], default='kmh', max_length=5, verbose_name='Top Speed Unit')),
                ('acceleration', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Acceleration Time')),
                ('acceleration_unit', models.CharField(choices=[('seconds', '0-100 km/h (seconds)'), ('quarter_mile', '1/4 mile time')], default='seconds', max_length=15, verbose_name='Acceleration Unit')),
                ('drivetrain', models.CharField(choices=[('rwd', 'Rear-Wheel Drive'), ('fwd', 'Front-Wheel Drive'), ('awd', 'All-Wheel Drive'), ('4wd', 'Four-Wheel Drive')], default='rwd', max_length=20, verbose_name='Drivetrain')),
                ('regions', models.CharField(choices=[('MS', 'Muscat'), ('DH', 'Dhofar'), ('BT', 'Al Batinah'), ('DA', 'Al Dakhiliya'), ('SH', 'Al Sharqiya'), ('BR', 'Al Buraimi'), ('ZU', 'Al Dhahirah'), ('MW', 'Musandam'), ('WR', 'Al Wusta')], default='MS', max_length=250)),
                ('cities', models.CharField(max_length=250, verbose_name='City')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('rental_period', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=10, verbose_name='Rental Period')),
                ('rental_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Rental Price')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('soldout', 'Soldout')], default='pending', max_length=20, verbose_name='Approval Status')),
                ('horsepower', models.PositiveIntegerField(blank=True, null=True, verbose_name='Horsepower')),
                ('torque', models.PositiveIntegerField(blank=True, null=True, verbose_name='Torque (Nm)')),
                ('lap_times', models.TextField(blank=True, null=True, verbose_name='Notable Lap Times')),
                ('production_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Production Number (for limited editions)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='luxury_vehicles', to=settings.AUTH_USER_MODEL)),
                ('images', models.ManyToManyField(blank=True, related_name='luxury_vehicle', to='oman_app.luxuryvehicleimage', verbose_name='Images')),
                ('videos', models.ManyToManyField(blank=True, related_name='luxury_vehicle', to='oman_app.luxuryvehiclevideo', verbose_name='Videos')),
            ],
        ),
    ]
