# Generated by Django 5.1.1 on 2025-04-10 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0121_luxuryvehicleimage_luxuryvehiclevideo_luxuryvehicle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='luxuryvehicle',
            name='acceleration_unit',
        ),
        migrations.RemoveField(
            model_name='luxuryvehicle',
            name='lap_times',
        ),
        migrations.RemoveField(
            model_name='luxuryvehicle',
            name='production_number',
        ),
    ]
