# Generated by Django 5.1.1 on 2025-04-10 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oman_app', '0122_remove_luxuryvehicle_acceleration_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='luxuryvehicle',
            name='description',
            field=models.TextField(default=1, verbose_name='Description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='luxuryvehicle',
            name='make',
            field=models.CharField(default=1, max_length=100, verbose_name='Manufacturer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='luxuryvehicle',
            name='year',
            field=models.PositiveIntegerField(default=1, verbose_name='Year'),
            preserve_default=False,
        ),
    ]
